export const cardConfig = [
  {
    id: 1,
    name: 'Narendra Modiiiii',
    handle: '@narendramodi',
    profileUrl: 'https://raw.githubusercontent.com/AboutReact/sampleresource/master/old_logo.png',
    currentStockValue: 938,
    percentChange: 22,
  },
  {
    id: 2,
    name: 'ab',
    handle: '@narendramodi',
    profileUrl: 'https://raw.githubusercontent.com/AboutReact/sampleresource/master/old_logo.png',
    currentStockValue: 2000,
    percentChange: 100,
  },
  {
    id: 3,
    name: 'Narendra Modi',
    handle: '@narendramodi',
    profileUrl: 'https://raw.githubusercontent.com/AboutReact/sampleresource/master/old_logo.png',
    currentStockValue: 222,
    percentChange: 22,
  },
  {
    id: 4,
    name: 'Narendra Modi',
    handle: '@narendramodi',
    profileUrl: 'https://raw.githubusercontent.com/AboutReact/sampleresource/master/old_logo.png',
    currentStockValue: 111,
    percentChange: -22,
  },
  {
    id: 5,
    name: 'Narendra Modi',
    handle: '@narendramodi',
    profileUrl: 'https://raw.githubusercontent.com/AboutReact/sampleresource/master/old_logo.png',
    currentStockValue: 10000,
    percentChange: -22,
  },
  {
    id: 6,
    name: 'Narendra Modi',
    handle: '@narendramodi',
    profileUrl: 'https://raw.githubusercontent.com/AboutReact/sampleresource/master/old_logo.png',
    currentStockValue: 10000,
    percentChange: -22,
  },
];
